# Basic settings
url: "bruno-montagem.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Bruno Montagem Express" # the name of your site, e.g. ACME Corp.

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gallery-generator
  - jekyll-menus
#paginate: 3
#paginate_path: service/page:num/
paginate: 3
paginate_path: posts/page:num/

#Gallery

gallery:
  dir: photos # Path to the gallery
  symlink: true # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos" # Title for gallery index page
  title_prefix: "Photos: " # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  auto_orient: false # False by defeault. When activated it rotates the images based on the exifr.
  sort_field:
    "date_time" # How to sort galleries on the index page.
    # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 410 # max width of thumbnails (in pixels)
    y: 200 # max height of thumbnails (in pixels)
# The following options are for individual galleries and totally optional.
#  galleries:
#    chile_trip:
#      best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
#    japan_trip:
#      best_image: IMG_0690.JPG
#      name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
#    awesome_stuff:
#      best_image: snaileo_gonzales.jpg
#      sort_reverse: true    # Reverse sort images in gallery.
#    secret_stuff:
#      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
#    with_info:
#      info:

#Permalink
permalink: /service/:title
source: .
destination: ./_site
# Compress CSS
sass:
  style: :compressed
  sass_dir: _sass

#Permalink format (/blog/ is ignored for pages)
#permalink: /post/:title
#permalink: :slug/

#Collections
collections:
  slides:
include:
  - _pages
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: false

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# Social

social:
  name: Bruno Montagem
  links:
    - https://twitter.com/Brunomontagem
    - https://www.facebook.com/Brunomontagem

# set some common post defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
